# Numpy Operations

In [33]:
import numpy as np


In [34]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [37]:
arr**arr

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [38]:
print(0/arr)

[nan  0.  0.  0.  0.  0.  0.  0.  0.  0.]


C:\Users\BRYAN\AppData\Local\Temp\ipykernel_1844\738647602.py:1: RuntimeWarning: invalid value encountered in divide
  print(0/arr)


In [39]:
print(1/arr)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


C:\Users\BRYAN\AppData\Local\Temp\ipykernel_1844\240748721.py:1: RuntimeWarning: divide by zero encountered in divide
  print(1/arr)


In [40]:
print(np.sin(arr))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [41]:
print(np.log(arr))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\BRYAN\AppData\Local\Temp\ipykernel_1844\873111080.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


# Pandas and its Capabilities in DataFrames

SERIES

#Extracting a column
df['NAme of column']
#Extracting multiple columns
df[['Col1,Col2']]
``


In [42]:
#Create a dataframe
import pandas as pd
import numpy as np

In [43]:
from numpy.random import randn

In [44]:
#Create a simple dataframe
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A -0.699828 -1.710455  1.096236 -0.304781
B -0.874960 -1.408155  0.213432 -1.574030
C  0.036245 -1.143095  0.061309  1.103996
D  0.457121  0.163486  0.539150  0.032720
E  1.746631  0.077517 -1.991350 -0.017114

# Columns Manipulation



In [45]:
df['New']=df['W']+df['Y']
df

W         X         Y         Z       New
A -0.699828 -1.710455  1.096236 -0.304781  0.396408
B -0.874960 -1.408155  0.213432 -1.574030 -0.661528
C  0.036245 -1.143095  0.061309  1.103996  0.097554
D  0.457121  0.163486  0.539150  0.032720  0.996271
E  1.746631  0.077517 -1.991350 -0.017114 -0.244719

In [46]:
#Dropping a column
df.drop('W',axis=1)

X         Y         Z       New
A -1.710455  1.096236 -0.304781  0.396408
B -1.408155  0.213432 -1.574030 -0.661528
C -1.143095  0.061309  1.103996  0.097554
D  0.163486  0.539150  0.032720  0.996271
E  0.077517 -1.991350 -0.017114 -0.244719

In [47]:
df

W         X         Y         Z       New
A -0.699828 -1.710455  1.096236 -0.304781  0.396408
B -0.874960 -1.408155  0.213432 -1.574030 -0.661528
C  0.036245 -1.143095  0.061309  1.103996  0.097554
D  0.457121  0.163486  0.539150  0.032720  0.996271
E  1.746631  0.077517 -1.991350 -0.017114 -0.244719

In [48]:
#dropping a column parmanently
df.drop('W',axis=1,inplace=True)

In [49]:
df

X         Y         Z       New
A -1.710455  1.096236 -0.304781  0.396408
B -1.408155  0.213432 -1.574030 -0.661528
C -1.143095  0.061309  1.103996  0.097554
D  0.163486  0.539150  0.032720  0.996271
E  0.077517 -1.991350 -0.017114 -0.244719

In [50]:
#For Dropping rows, just change the axis name or index

In [51]:
df.shape

(5, 4)

# Extracting rows
You can use ".loc" when using names for rows or ".iloc" when using an index  for extraction

In [52]:
#Extracting row A
df.loc['A']

X     -1.710455
Y      1.096236
Z     -0.304781
New    0.396408
Name: A, dtype: float64

In [53]:
df.iloc[0]

X     -1.710455
Y      1.096236
Z     -0.304781
New    0.396408
Name: A, dtype: float64

In [54]:
#Extracting rows and columns(Intersection)
print(df.loc[['B','A']])

          X         Y         Z       New
B -1.408155  0.213432 -1.574030 -0.661528
A -1.710455  1.096236 -0.304781  0.396408


In [55]:
#Extracting the intersection
df.loc[['A','B'],['Z','Y']]

Z         Y
A -0.304781  1.096236
B -1.574030  0.213432

Done.

# Conditional selection.

In [58]:
#returns those True values as values and false as NaN


In [59]:
#return dataframe with values where it is greater than 0 in one line of code without boolean
df[df>0]

X         Y         Z       New
A       NaN  1.096236       NaN  0.396408
B       NaN  0.213432       NaN       NaN
C       NaN  0.061309  1.103996  0.097554
D  0.163486  0.539150  0.032720  0.996271
E  0.077517       NaN       NaN       NaN

In [ ]:
df

In [63]:
#access the column in Y where the values is greater than 0
df[df['Y']>0]

X         Y         Z       New
A -1.710455  1.096236 -0.304781  0.396408
B -1.408155  0.213432 -1.574030 -0.661528
C -1.143095  0.061309  1.103996  0.097554
D  0.163486  0.539150  0.032720  0.996271

In [ ]:
#access the column in w where the values is greater than 0 AND RETURN THE X COLUMN
df[df['Y']>-0.1]['X']

In [64]:
#uSING MULTIPLE CONDITIONS to access columns
#here, the two conditions are met and returns the values
df[(df['Y']>-0.1) & (df['X']>0)]

X        Y        Z       New
D  0.163486  0.53915  0.03272  0.996271

# HIERACHY AND MULTIPLE INDEXING

In [65]:
outside=['G1','G1', 'G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))
hier_index=pd.MultiIndex.from_tuples(hier_index)

In [66]:
#creates an index and combines it with associated element
list(zip(outside,inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [67]:
#create the dataframe
df=pd.DataFrame(randn(6,2), hier_index,['A','B'])
df
#here 6 and 2 represent

A         B
G1 1 -0.820714 -0.192612
   2 -1.191533  0.994911
   3  2.136372 -0.416936
G2 1  0.184954  0.927806
   2 -0.338617 -0.961495
   3 -0.673904 -0.306622

In [68]:
#calling datA from the above dataframw

In [69]:
df.loc['G1']

A         B
1 -0.820714 -0.192612
2 -1.191533  0.994911
3  2.136372 -0.416936

In [70]:
df.loc['G1'].iloc[1]

A   -1.191533
B    0.994911
Name: 2, dtype: float64

In [71]:
#Assigning the indexes a header- for easy identification
df.index.names=['Groups','Level']
df

A         B
Groups Level                    
G1     1     -0.820714 -0.192612
       2     -1.191533  0.994911
       3      2.136372 -0.416936
G2     1      0.184954  0.927806
       2     -0.338617 -0.961495
       3     -0.673904 -0.306622

In [72]:
#Accessisng an individual value.-Here we have accessed only one.
df.loc['G1'].loc[3]['B']

-0.4169355953587189

In [73]:
#using the cross section function
#we access the 1(s) in both Groups
#This is useful where its tricky to use loc method.
df.xs(1,level='Level')

A         B
Groups                    
G1     -0.820714 -0.192612
G2      0.184954  0.927806